### PR TITLE
66 fix registrator logic

### LINKED ISSUE #66: Fix Registrator logic
1) Add functions to registrator_config to read wifi_is_set, wifi_ssid, wifi_pass
2) Change ESP32_WIFI_ADAPTER_ENABLED to wifi_is_set
3) Move RegistratorAction to a separate file
4) Add configuration of the state header file path via the cli

### PR DESCRIPTION
**Pull request by v2016e**

### CODE REVIEW

File: config/file_system_init.h [hunk 1]
```diff
@@ -3,193 +3,337 @@
 
 #include <array>
```
Comment (BartolomeyKant) [inline config/file_system_init.h:4]: This file should not be saved. Maybe its better to generate it for each example.

**Review by BartolomeyKant — APPROVED** [review]
